services:
  # --- БАЗЫ ДАННЫХ И ИНФРАСТРУКТУРА ---
  app-db:
    image: postgres:16
    restart: always
    environment:
      - POSTGRES_DB=${APP_POSTGRES_DB}
      - POSTGRES_USER=${APP_POSTGRES_USER}
      - POSTGRES_PASSWORD=${APP_POSTGRES_PASSWORD}
    volumes:
      - app_postgres_data:/var/lib/postgresql/data/
    env_file: .env

  gt-db:
    image: postgres:16-alpine
    restart: unless-stopped
    environment:
      - POSTGRES_DB=${GT_POSTGRES_DB}
      - POSTGRES_USER=${GT_POSTGRES_USER}
      - POSTGRES_PASSWORD=${GT_POSTGRES_PASSWORD}
    volumes:
      - gt_pg_data:/var/lib/postgresql/data
    env_file: .env

  redis:
    image: redis:7-alpine
    restart: always

  # --- ТВОЕ ПРИЛОЖЕНИЕ ---
  web:
    build:
      context: .
      dockerfile: app/Dockerfile
    restart: always
    entrypoint: /home/rec_shop/entrypoint.sh
    ports:
      - "8000:8000"
    env_file: .env
    environment:
      - MODE=PROD
      - DATABASE_URL=${DATABASE_URL}
      - IS_CELERY_WORKER=False
    depends_on:
      - app-db
      - redis
    extra_hosts:
      - "host.docker.internal:host-gateway"

  worker:
    build:
      context: .
      dockerfile: app/Dockerfile
    restart: always
    # Добавляем -P solo для стабильности asyncio на Windows/WSL
    command: celery -A app.utils.celery_tasks:celery_app worker --loglevel=info -E -P solo
    env_file: .env
    environment:
      - MODE=PROD
      - IS_CELERY_WORKER=True
      - PYTHONPATH=/home/rec_shop
      - DATABASE_URL=${DATABASE_URL}
    depends_on:
      - app-db
      - redis
    extra_hosts:
      - "host.docker.internal:host-gateway"

  flower:
    build:
      context: .
      dockerfile: app/Dockerfile
    restart: always
    command: celery -A app.utils.celery_tasks:celery_app flower --port=5555 --prometheus-metrics
    ports:
      - "5555:5555"
    env_file: .env
    environment:
      - MODE=PROD
      - PYTHONPATH=/home/rec_shop
    depends_on:
      - redis
      - worker

  # --- GLITCHTIP ---
  glitchtip:
    image: glitchtip/glitchtip
    restart: unless-stopped
    ports:
      - "8080:8000"
    env_file: .env
    environment:
      - DATABASE_URL=${GT_DATABASE_URL}
      - GLITCHTIP_DOMAIN=http://localhost:8080
      - ALLOWED_HOSTS=localhost,glitchtip,127.0.0.1,host.docker.internal
      - ENABLE_OPEN_USER_REGISTRATION=True
    depends_on:
      - gt-db
      - redis

  gt-worker:
    image: glitchtip/glitchtip
    command: ./bin/run-celery.sh
    restart: unless-stopped
    env_file: .env
    environment:
      - DATABASE_URL=${GT_DATABASE_URL}
    depends_on:
      - gt-db
      - redis

  # --- МОНИТОРИНГ (МЕТРИКИ) ---
  prometheus:
    image: prom/prometheus
    restart: always
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    depends_on:
      - web
      - flower

  grafana:
    image: grafana/grafana
    restart: always
    ports:
      - "3000:3000"
    user: "472"
    depends_on:
      - prometheus
      - loki
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana_datasources.yml:/etc/grafana/provisioning/datasources/datasources.yaml:ro
      - ./grafana_dashboards_config.yml:/etc/grafana/provisioning/dashboards/provider.yaml:ro
      - ./grafana_dashboards:/var/lib/grafana/dashboards:ro

  # --- МОНИТОРИНГ (ЛОГИ) ---
  loki:
    image: grafana/loki:latest
    restart: always
    ports:
      - "3100:3100"
    volumes:
      - loki_data:/loki
      - ./loki-config.yaml:/etc/loki/local-config.yaml

  promtail:
    image: grafana/promtail:latest
    restart: always
    user: root
    volumes:
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./promtail-config.yaml:/etc/promtail/config.yaml
    command: -config.file=/etc/promtail/config.yaml
    depends_on:
      - loki

volumes:
  app_postgres_data:
  gt_pg_data:
  grafana_data:
  loki_data:
  prometheus_data:
  uploads:

