scrape_configs:
  - job_name: 'fastapi'
    static_configs:
      - targets: ['web:8000']

  - job_name: 'celery'
    static_configs:
      - targets: ['flower:5555']





#global:
#  scrape_interval: 15s # Как часто собирать данные
#
#scrape_configs:
#  - job_name: 'fastapi'
#    static_configs:
#      - targets: ['localhost:8000'] # если запускаете без Docker
#    #  - targets: ['host.docker.internal:8000'] # если запускаете через Docker
#
#  - job_name: 'celery-flower'
#    static_configs:
#      - targets: ['host.docker.internal:5555'] # Метрики из Flower
