global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'fastapi'
    static_configs:
      - targets: ['web:8000']
        labels:
          app_name: 'fastapi'

  - job_name: 'celery'
    metrics_path: '/flower/metrics'
    static_configs:
      - targets: ['flower:5555']

